# Stage 1: Install dependencies
FROM python:3.10-alpine AS builder
COPY ./requirements.txt /home
RUN pip install --no-cache-dir -r /home/requirements.txt

# Stage 2: Final image
FROM python:3.10-alpine
EXPOSE 8080
WORKDIR /home

# Copy the installed packages from the builder stage
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages

# Copy the local repository files to the container
COPY . /home/ChatGPT-Telegram-Bot

# Clean temporary files
RUN rm -rf /tmp/*

# Run the bot script
ENTRYPOINT ["python", "-u", "/home/ChatGPT-Telegram-Bot/bot.py"]
